# Generated by Django 5.1.6 on 2025-03-07 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.categories')),
                ('en_word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.enwords')),
                ('ru_word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.ruwords')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count_words', models.IntegerField()),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.ratings')),
            ],
        ),
        migrations.CreateModel(
            name='Userdictionaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_choose_ru', models.BooleanField(default=False)),
                ('translate_choose_en', models.BooleanField(default=False)),
                ('translate_write_ru', models.BooleanField(default=False)),
                ('translate_write_en', models.BooleanField(default=False)),
                ('write_word_using_audio', models.BooleanField(default=False)),
                ('is_learn', models.BooleanField(default=False)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.dictionary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.users')),
            ],
        ),
    ]
